server:
  port: 1111

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90 #表示服务失效时间，默认为90秒
    lease-renewal-interval-in-seconds: 30 #表示服务续约任务的调用间隔时间，默认为30秒
  client:
    register-with-eureka: false #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    fetch-registry: false #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #参数用来关闭保护机制，线上需要开启

